### ISSUE TITLE
Consider unpackage-ing

### ISSUE THREAD

**Issue by kelle** [sambit-giri/AstronomyCalc#5]
The code here is useful for exploring various cosmological concepts however, much of the code in the actual AstronomyCalc package should be replaced with functions available in other widely-used packages such as Astropy and emcee.  Instead of bundling this work as a new package, I would recommend publishing as a collection of notebooks.

Submitted as part of JOSE Review.
openjournals/jose-reviews#261

**Comment by sambit-giri** [comment]
I agree that there are several highly optimised packages out there for the calculations presented in the tutorials, which could be good for the students to learn to use. However, the key goal of this package is to show the students how the concepts or equations taught in the classroom can be coded up and give them tasks where they would be asked to use some functions or go beyond it. Using the widely-used packages during teaching may help them learn using these packages but not developing them.

**Comment by sambit-giri** [comment]
I am considering to instead extend the notebook with advanced examples using the widely-used packages. This would direct them to try out these packages after learning the basic methods. @kelle what do you think?

**Comment by sambit-giri** [comment]
I want to refer to the reply [here](https://github.com/openjournals/jose-reviews/issues/261#issuecomment-2527790360) and the discussion post the reply. Instead of complete unpackage-ing, this package is a collection of several simple implemenation of the methods used in astronomy that can be introduced to students. In the tutorial notebooks, I will mention the more oprimised and widely used packages that the interested students can explore.
